configuration: 
  - Release
  - Debug

version: '1.2.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-pre"

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore

build:
  publish_nuget: true

deploy:
  provider: NuGet
  on:
	branch: develop
  server: https://ci.appveyor.com/nuget/design2code/api/v2/package
  api_key: 
    secure: DDdqquza1rjvPbT/uXPydYO0re75ik5zFilZ55nEdQU=
  artifact: /.*\.nupkg/

deploy:
  provider: NuGet
  on:
    branch: master
  api_key: 
    secure: ++chmJA4vMpQ8q/psc3fh/lAX2eLtxLCguPvOmUnPRLIRmWCbgGw0OAMATOlvXH3
  artifact: /.*\.nupkg/