configuration: Release
version: '1.0.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

artifacts:
  - path: '*.nupkg'

build:
  publish_nuget: true

after_build:
  - nuget pack %APPVEYOR_PROJECT_NAME$\%APPVEYOR_PROJECT_NAME$.nuspec -Version %appveyor_build_version%
  - appveyor PushArtifact %APPVEYOR_PROJECT_NAME$.%appveyor_build_version%.nupkg

deploy:
  provider: NuGet
  api_key: ++chmJA4vMpQ8q/psc3fh/lAX2eLtxLCguPvOmUnPRLIRmWCbgGw0OAMATOlvXH3
  artifact: /.*\.nupkg/