configuration: 
  - Release

version: '1.2.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore

nuget:
  account_feed: true
  project_feed: true

build:
  publish_nuget: true
  project: node3.1.sln 

deploy:
  provider: NuGet
  on:
    branch: master
  api_key: 
    secure: ++chmJA4vMpQ8q/psc3fh/lAX2eLtxLCguPvOmUnPRLIRmWCbgGw0OAMATOlvXH3
  artifact: /.*\.nupkg/

#test:
#  categories:
#    except:
#      - IntegrationTest