configuration: Release
version: '1.0.{build}'

before_build:
  - nuget restore

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key: ++chmJA4vMpQ8q/psc3fh/lAX2eLtxLCguPvOmUnPRLIRmWCbgGw0OAMATOlvXH3