configuration: 
  - Release

version: '1.2.{build}'

build_script:
  msbuild node3.1.sln /Configuration="Debug;Release;" /target="x86;x64;AnyCPU" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

environment:
  COVERALLS_REPO_TOKEN:
    secure: 9Quk4g9ozgWrhZOjsuEXN1bCIKbMK8xcizjTTt9m/rCyex3RRVJN70ZXELeGLbJn

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore

nuget:
  account_feed: true
  project_feed: true

build:
  publish_nuget: true
  project: node3.1.sln 

after_build:
  - cmd: nuget pack dev\NativeLibrary\NativeLibrary.nuspec -version %APPVEYOR_BUILD_VERSION%
  - ps: Get-ChildItem .\SBSuite.NativeLibrary.*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }


deploy:
  provider: NuGet
  on:
    branch: master
  api_key: 
    secure: ++chmJA4vMpQ8q/psc3fh/lAX2eLtxLCguPvOmUnPRLIRmWCbgGw0OAMATOlvXH3

test_script: 
  - ps: ./test-and-cover.ps1
  

test:
  categories:
    except:
      - IntegrationTest