configuration: Release
version: '1.0.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

artifacts:
  - path: '$(appveyor_project_name)\*.nupkg'
  - name: nupkg

build:
  publish_nuget: true

deploy:
  provider: NuGet
  api_key: 
    secure: ++chmJA4vMpQ8q/psc3fh/lAX2eLtxLCguPvOmUnPRLIRmWCbgGw0OAMATOlvXH3
  artifact: /.*\.nupkg/